<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12.0</LangVersion>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <PropertyGroup>
        <!--NuGet Package settings:-->
        <Title>S4Forge SDK</Title>
        <PackageId>S4Forge.SDK</PackageId>
        <Authors>WizzardMaker</Authors>
        <Description>
            Build scripts and helper for generating Forge manifests and installing files into the S4 directory
        </Description>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageOutputPath>$(SolutionDir)BUILD\NuGet\</PackageOutputPath>
        <FileVersion>$(AssemblyVersion)</FileVersion>
        <Version>$(AssemblyVersion)</Version>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>

        <RepositoryUrl>https://github.com/Settlers-4-Reforged/S4Forge.SDK</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>

        <TargetsForTfmSpecificBuildOutput>
            $(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage
        </TargetsForTfmSpecificBuildOutput>
        <BuildOutputTargetFolder>tasks</BuildOutputTargetFolder>
        <NoWarn>NU5100</NoWarn>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>

        <GenerateDependencyFile>true</GenerateDependencyFile>
    </PropertyGroup>

    <!-- This is the target we defined above. Its purpose is to add all of our PackageReference and ProjectReference's runtime assets to our package output.  -->
    <Target Name="CopyProjectReferencesToPackage" DependsOnTargets="ResolveReferences">
        <ItemGroup>
            <!-- The TargetPath is the path inside the package that the source file will be placed. This is already precomputed in the ReferenceCopyLocalPaths items' DestinationSubPath, so reuse it here. -->
            <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths)" TargetPath="%(ReferenceCopyLocalPaths.DestinationSubPath)" />
        </ItemGroup>
    </Target>

    <!-- This target adds the generated deps.json file to our package output -->
    <Target Name="AddBuildDependencyFileToBuiltProjectOutputGroupOutput" BeforeTargets="BuiltProjectOutputGroup" Condition=" '$(GenerateDependencyFile)' == 'true'">
        <ItemGroup>
            <BuiltProjectOutputGroupOutput Include="$(ProjectDepsFilePath)" TargetPath="$(ProjectDepsFileName)" FinalOutputPath="$(ProjectDepsFilePath)" />
        </ItemGroup>
    </Target>

    <ItemGroup>
        <Content Include="Manifest.targets" PackagePath="build\" />
        <Content Include="Manifest.props" PackagePath="build\" />
        <Content Include="Release.targets" PackagePath="build\" />
        <Content Include="S4Forge.SDK.targets" PackagePath="build\" />
        <Content Include="S4Forge.SDK.props" PackagePath="build\" />
    </ItemGroup>

    <ItemGroup>
      <None Include=".github\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.11.48" PrivateAssets="all" ExcludeAssets="Runtime" />
    </ItemGroup>


    <Choose>
        <When Condition="'$(SolutionName)'=='S4ModdingFramework'">
            <ItemGroup>
                <ProjectReference Include="..\S4ForgeUpdater\ForgeUpdater\ForgeUpdater.csproj" />
            </ItemGroup>
        </When>
        <Otherwise>
            <ItemGroup>
                <PackageReference Include="S4Forge.Updater" Version="0.6.*" />
            </ItemGroup>
        </Otherwise>
    </Choose>
    
</Project>
